---
name: "Creates a GitHub release and uploads a binary"
description: |
  This action creates a release and uploads a binary.
author: martoc
runs:
  using: "composite"
  steps:
    - name: Release
      shell: bash
      run: |
        GITHUB_TOKEN=${{ github.token }}
        GITHUB_REPOSITORY=${{ github.repository }}
        RESPONSE=$(curl -sSL -H "Authorization: token $GITHUB_TOKEN" -H "Content-Type: application/json" -X POST -d "{\"tag_name\":\"$TAG_NAME\",\"name\":\"$TAG_NAME\"}" "https://api.github.com/repos/$GITHUB_REPOSITORY/releases")
        RELEASE_ID=$(echo "$RESPONSE" | jq -r '.id')
        if [ "$RELEASE_ID" = "" ]; then
          echo "RESPONSE=$RESPONSE"
          echo "Failed to create github release"
          exit 1
        fi
        if [ -z "$BIN_NAMES" ]; then
          echo "No binaries to upload"
        else
          for BIN_NAME in $BIN_NAMES; do
            RESPONSE=$(curl -sSL -H "Authorization: token $GITHUB_TOKEN" -H "Content-Type: application/json" --data-binary @"target/builds/$BIN_NAME" "https://uploads.github.com/repos/$GITHUB_REPOSITORY/releases/$RELEASE_ID/assets?name=$BIN_NAME")
            ASSET_ID="$(echo "$RESPONSE" | jq -r '.id')"
            if [[ "$ASSET_ID" != null ]]; then
              echo "Asset uploaded successfully!: ASSET_ID=$ASSET_ID"
            else
              echo "RESPONSE=$RESPONSE"
              echo "Failed to upload asset. RESPONSE: $RESPONSE"
              exit 1
            fi
          done
        fi
